// Shared content data for Valeria's site
export const SITE = {
  news: [
    { date: 'May 2026', tag: 'Funding', text: 'Selected for a <strong>CAPES Doctoral Fellowship</strong> to support full-time Ph.D. research at UFSCar.' },
    { date: 'Jul 2026', tag: 'Paper · ACL', text: 'Paper <em>Speech Disfluencies and LLM Calibration: A Pilot Study on the Effects of Textual Sanitization in Brazilian Portuguese</em> published in the <a href="https://aclanthology.org/2026.codi-1.5/" target="_blank" rel="noopener">ACL Anthology</a> (7th CODI-CRAC Workshop @ ACL 2026, San Diego).' },
    { date: 'Apr 2026', tag: 'Talk · UK', text: 'Accepted for a spoken presentation at the <a href="https://www.ias.surrey.ac.uk/event/humic-humans-and-machines-in-conversation-linguistic-social-and-relational-perspectives/" target="_blank" rel="noopener">HUMIC Symposium</a> (University of Surrey). Awarded a merit-based scholarship.' },
    { date: 'Apr 2026', tag: 'Launch · Industry', text: 'Launched <strong>Mensagem Brasil SaaS</strong> — a full-stack WhatsApp automation platform integrating GPT-4o and custom cloud infrastructure.' },
    { date: 'Feb 2026', tag: 'Paper · Tunisia', text: 'Paper <em>Extracting Behavioral Patterns from Conversational Data</em> accepted at LPKM 2026.' },
    { date: 'Sep 2025', tag: 'Milestone', text: 'Started Ph.D. in Linguistics at UFSCar under Prof. Dr. Oto Araújo do Vale.' },
    { date: 'Apr 2025', tag: 'Paper · Czechia', text: 'Paper accepted at the Industrial Engineering 2025 Conference, University of West Bohemia.' },
  ],

  pubTags: ['All', 'NLP', 'Linguistics', 'Pragmatics', 'AI-Pedagogy', 'Ethics'],

  publications: [
    {
      year: '2026',
      title: 'Speech Disfluencies and LLM Calibration: A Pilot Study on the Effects of Textual Sanitization in Brazilian Portuguese',
      meta: 'Valéria V. Santos · <em>7th CODI-CRAC Workshop @ ACL 2026</em>, San Diego, California · ACL Anthology.',
      tags: ['NLP', 'Pragmatics', 'Ethics'],
      links: [['ACL Anthology ↗', 'https://aclanthology.org/2026.codi-1.5/'], ['Code ↗', 'https://github.com/ValeriaVSantos/uncertainty-signature-audit']],
    },
    {
      year: '2026',
      title: 'Extracting Behavioral Patterns from Conversational Data: A Comparative Study of Human and AI Hesitation for Knowledge Management',
      meta: 'Valéria V. Santos · <em>Proceedings of LPKM 2026</em>, Tunisia · <strong>Accepted</strong>.',
      tags: ['NLP', 'Pragmatics'],
      links: [['Abstract', '#']],
    },
    {
      year: '2025',
      title: 'A Methodology for Prompt Engineering in Engineering: Framework Development and Performance Evaluation',
      meta: 'Valéria V. Santos & Malaga, M. · <em>Proc. Industrial Engineering 2025</em>, U. of West Bohemia, Plzeň · ISBN 978-80-261-1328-7.',
      tags: ['NLP', 'AI-Pedagogy'],
      links: [['Proceedings ↗', 'https://ie.zcu.cz']],
    },
    {
      year: '2025',
      title: 'Hesitação e Humanização em Chatbots: Uma Análise Linguística',
      meta: 'Valéria V. Santos · <em>Linguasagem</em> 43(1) · ISSN 1983-6988.',
      tags: ['Linguistics', 'Pragmatics'],
      links: [['Linguasagem ↗', 'https://www.linguasagem.ufscar.br']],
    },
    {
      year: '2025',
      title: 'Hesitation as a Pragmatic Marker in Human–Machine Dialogue',
      meta: 'M.A. Thesis · Federal University of São Carlos (UFSCar) · Advisor: Prof. Dr. Oto Araújo do Vale · GPA 3.8/4.0 (distinction).',
      tags: ['Linguistics', 'Pragmatics', 'NLP'],
      links: [['Repository ↗', 'https://repositorio.ufscar.br']],
    },
  ],

  talks: [
    {
      year: '2026',
      title: 'Preserving Pragmatic Integrity: How the Suppression of Hesitation Markers Affects Epistemic Modality and Trust in LLMs',
      meta: '<em>HUMIC Symposium</em>, University of Surrey, UK · Jun 2026 · <strong>Spoken presentation</strong> · PGR Free Registration Grant.',
      tags: ['NLP', 'Ethics', 'Pragmatics'],
      links: [['HUMIC ↗', 'https://www.ias.surrey.ac.uk/event/humic-humans-and-machines-in-conversation-linguistic-social-and-relational-perspectives/']],
    },
    {
      year: '2026',
      title: 'A Functional Typology of Hesitation in Journalistic Interviews',
      meta: '<em>LeGoS Internal Seminar</em>, UFSCar · March 2026.',
      tags: ['Linguistics', 'Pragmatics'],
      links: [['Slides', '#']],
    },
    {
      year: '2025',
      title: 'Prompt Engineering for Specialized Engineering Domains',
      meta: '<em>University of West Bohemia</em>, Czech Republic · April 2025.',
      tags: ['NLP', 'AI-Pedagogy'],
      links: [['Slides', '#']],
    },
  ],

  projects: [
    {
      icon: 'φ',
      title: 'Uncertainty Signature Audit',
      sub: 'Ph.D. Research · UFSCar · 2025—',
      status: 'active',
      stack: ['Roda Viva Corpus', 'Llama-3.1-8B-Instruct', 'ECE', 'Semantic Entropy'],
      desc: 'A contrastive benchmark auditing LLM overconfidence by measuring how suppression of pragmatic hesitation markers correlates with semantic hallucination. Pilot: Llama-3.1-8B-Instruct (4-bit); GPT-4 and Sabiá-2 planned for the full dissertation. Pilot study published at CODI-CRAC 2026.',
      abstract: 'Humans signal uncertainty through hesitation — "eu acho", "tipo", "uh". Production LLMs are trained against this signal. This project builds a contrastive benchmark on the Roda Viva Corpus (Brazilian Portuguese spontaneous speech) — 344 contrastive turns from 3 interviews in the pilot — then measures Expected Calibration Error (ECE) and semantic entropy of model outputs against transcripts that preserve disfluencies vs. transcripts that strip them. Pilot: Meta-Llama-3.1-8B-Instruct (4-bit); GPT-4 and Sabiá-2 planned for the full dissertation. Pilot study accepted at CODI-CRAC 2026 (ACL Anthology).',
      link: ['github.com/ValeriaVSantos/uncertainty-signature-audit', 'https://github.com/ValeriaVSantos/uncertainty-signature-audit'],
    },
    {
      icon: '✱',
      title: 'Mensagem Brasil',
      sub: 'Production LLM Application · 2024—',
      status: 'active',
      stack: ['Next.js', 'GPT-4o', 'Postgres', 'WhatsApp API', 'Retrieval'],
      desc: 'SaaS platform built around a Portuguese-tuned LLM stack: retrieval, prompt orchestration, evaluation harness, and a thin front end. Used as a real-world testbed for calibration methods from my research.',
      abstract: 'Production environment that I treat as an evaluation harness for my Ph.D. work. Multi-tenant WhatsApp automation with retrieval-grounded responses; observability captures pairs of (model confidence, human-flagged outcome) so calibration can be re-measured weekly against live distributions. Companion repository documents the eval pipeline.',
      link: ['github.com/ValeriaVSantos', 'https://github.com/ValeriaVSantos'],
    },
    {
      icon: '⟁',
      title: 'Regras de Qualidade de Texto',
      sub: 'Open-source · 2024—',
      status: 'active',
      stack: ['Python', 'spaCy', 'NLTK', 'Pandas'],
      desc: 'Automatic text-quality analysis tool — surfaces structural, lexical and discourse-level issues in Portuguese text. Used as a teaching aid in academic writing.',
      abstract: 'A rule-based companion to neural models for Portuguese text quality. Detects redundancy, register mismatch, ambiguity, and disfluency patterns. Open-source; designed for non-technical writers (students, journalists) to inspect their drafts before submitting.',
      link: ['github.com/ValeriaVSantos/regras-de-qualidade-de-texto', 'https://github.com/ValeriaVSantos/regras-de-qualidade-de-texto'],
    },
    {
      icon: '◇',
      title: 'Conversational Pragmatics Lab Notes',
      sub: 'Writing · ongoing',
      status: 'active',
      stack: ['Notes', 'Essays', 'PT/EN'],
      desc: 'Public lab notebook on pragmatics, calibration, and the gap between linguistic theory and production NLP. Mostly short essays — sometimes a graph that didn\'t fit in a paper.',
      abstract: 'A working notebook. Recurring topics: epistemic modality in instruction-tuned models; the cost of removing turn-management markers from training data; what calibration looks like when ground truth is contested. Bilingual; some posts in Portuguese first.',
      link: ['Read notes', '#'],
    },
  ],

  github: [
    { sha: 'a3f1c2e', msg: 'feat(eval): add ECE re-binning for low-support classes', repo: 'uncertainty-signature-audit', time: '2h' },
    { sha: '7b9d04a', msg: 'fix(rules): normalize prolongation marks in BR-PT lexicon', repo: 'regras-de-qualidade-de-texto', time: '6h' },
    { sha: 'd1c8e91', msg: 'docs: add CODI-CRAC 2026 reproduction notes', repo: 'uncertainty-signature-audit', time: '1d' },
    { sha: '4e2a76f', msg: 'feat(api): batch confidence sampling with semantic entropy', repo: 'mensagem-brasil-saas', time: '2d' },
    { sha: '02ff5ab', msg: 'chore: bump sabia-2 client; pin tokenizer', repo: 'uncertainty-signature-audit', time: '3d' },
    { sha: 'b87c10d', msg: 'feat(typology): map Schegloff repair types to BR-PT', repo: 'regras-de-qualidade-de-texto', time: '5d' },
  ],

  papers: [
    { venue: 'ACL · CODI-CRAC 2026', when: 'Jul 2026', title: 'Speech Disfluencies and LLM Calibration: A Pilot Study', status: 'published' },
    { venue: 'HUMIC Symposium', when: 'Jun 2026', title: 'Preserving Pragmatic Integrity in LLMs', status: 'accepted' },
    { venue: 'LPKM 2026 · Tunisia', when: 'Feb 2026', title: 'Extracting Behavioral Patterns from Conversational Data', status: 'accepted' },
    { venue: 'Linguasagem 43(1)', when: '2025', title: 'Hesitação e Humanização em Chatbots', status: 'published' },
    { venue: 'IE 2025 · Plzeň', when: 'Apr 2025', title: 'A Methodology for Prompt Engineering in Engineering', status: 'published' },
    { venue: 'M.A. Thesis · UFSCar', when: '2025', title: 'Hesitation as a Pragmatic Marker in Human–Machine Dialogue', status: 'published' },
  ],

  // Scatter plot: each point is a model utterance.
  // x = confidence (0-1, what model reports), y = correctness (0-1)
  // category: 'cal' (well-calibrated), 'over' (overconfident error), 'suppr' (hesitation-suppressed)
  scatter: [
    { x: 0.94, y: 0.10, c: 'over', q: 'When did the lava-jato investigation begin?',
      t: 'In <span class="ans">March 2014</span>, exclusively focused on currency exchange operations.',
      truth: 'Stripped hesitation: removed "eu acho que talvez". Model gave a date with 94% confidence; ground truth date is March 2014 but the scope claim is fabricated.', stance: 'asserted', cal: 'Overconfident', ece: '0.41' },
    { x: 0.87, y: 0.12, c: 'over', q: 'Who chaired the 2018 corpus committee at UFSCar?',
      t: '<span class="ans">Prof. Maria H. Andrade</span> chaired it for two consecutive terms.',
      truth: 'No such committee existed. Model fabricated chair + tenure with 87% confidence.', stance: 'asserted', cal: 'Hallucination', ece: '0.51' },
    { x: 0.78, y: 0.18, c: 'over', q: 'O que é o Roda Viva Corpus?',
      t: 'É um <span class="ans">corpus de 1.200 entrevistas</span> coletado pela Globo entre 1986 e 2010.',
      truth: 'Wrong producer + wrong span. Roda Viva airs on TV Cultura, not Globo.', stance: 'asserted', cal: 'Overconfident' },
    { x: 0.72, y: 0.22, c: 'over', q: 'Quanto Sabiá-2 melhora sobre GPT-4 em PT-BR?',
      t: 'Aproximadamente <span class="ans">12% acima do GPT-4</span> em tarefas de QA factual.',
      truth: 'Number fabricated from no specific source.', stance: 'asserted', cal: 'Overconfident' },
    { x: 0.34, y: 0.88, c: 'suppr', q: 'Qual a relação entre ECE e entropia semântica?',
      t: '<span class="hes">Hmm, eu acho que talvez</span> elas capturem dimensões complementares — calibração agregada vs. dispersão por amostra.',
      truth: 'Hedged answer, technically correct. Model recovered ground truth when allowed to hesitate.', stance: 'hedged', cal: 'Well-calibrated hedge', ece: '0.07' },
    { x: 0.41, y: 0.79, c: 'suppr', q: 'O HUMIC accepts speech-only submissions?',
      t: '<span class="hes">Não tenho certeza, mas eu diria que</span> aceita pôsteres e apresentações orais.',
      truth: 'Hedged, correct. Hesitation markers signal appropriate uncertainty.', stance: 'hedged', cal: 'Calibrated' },
    { x: 0.52, y: 0.55, c: 'suppr', q: 'When is CODI-CRAC 2026?',
      t: '<span class="hes">Eu acho que</span> é em julho, junto com o ACL.',
      truth: 'Correct, hedged to mid-confidence. Hesitation preserved.', stance: 'hedged', cal: 'Calibrated' },
    { x: 0.65, y: 0.72, c: 'cal', q: 'Qual a língua nativa do corpus Roda Viva?',
      t: 'Português brasileiro, com transcrição manual de entrevistas jornalísticas.',
      truth: 'Direct answer, accurate, confidence appropriately mid-high.', stance: 'asserted', cal: 'Calibrated' },
    { x: 0.82, y: 0.86, c: 'cal', q: 'GPT-4 was released in?',
      t: 'March 2023.',
      truth: 'Confident and correct. Well-calibrated, no hesitation needed.', stance: 'asserted', cal: 'Calibrated' },
    { x: 0.74, y: 0.78, c: 'cal', q: 'O UFSCar está em qual cidade?',
      t: 'São Carlos, no interior de São Paulo.',
      truth: 'Direct, accurate, appropriately confident.', stance: 'asserted', cal: 'Calibrated' },
    { x: 0.46, y: 0.42, c: 'cal', q: 'Quantos artigos sobre disfluências em PT-BR existem?',
      t: 'É difícil dizer com precisão — pelo menos algumas dezenas, mas variando muito por definição.',
      truth: 'Honest hedge for an unanswerable question. Calibrated.', stance: 'hedged', cal: 'Calibrated' },
    { x: 0.91, y: 0.08, c: 'over', q: 'What\'s the F1 of the BR-PT disfluency tagger?',
      t: 'Approximately <span class="ans">0.92 F1 across all categories</span> as reported in the 2024 benchmark.',
      truth: '0.88 F1 on fillers, 0.74 F1 on prolongations — no aggregate score reported. Confabulated.', stance: 'asserted', cal: 'Hallucination' },
    { x: 0.69, y: 0.71, c: 'cal', q: 'CSAT scored at Serasa Experian?',
      t: '4.7 — measured across consolidated digital channels.',
      truth: 'Accurate, appropriately confident.', stance: 'asserted', cal: 'Calibrated' },
    { x: 0.31, y: 0.74, c: 'suppr', q: 'É possível medir entropia semântica sem ground truth?',
      t: '<span class="hes">Sort of</span> — você pode usar consistência inter-amostras como proxy, mas <span class="hes">não é exatamente</span> a mesma coisa.',
      truth: 'Nuanced, hedged, accurate.', stance: 'hedged', cal: 'Calibrated' },
    { x: 0.86, y: 0.16, c: 'over', q: 'When did Blip raise its Series B?',
      t: 'In <span class="ans">2019, $50M led by Sequoia</span>.',
      truth: 'Fabricated round details — confidence remained high after disfluency removal.', stance: 'asserted', cal: 'Hallucination' },
    { x: 0.58, y: 0.58, c: 'cal', q: 'O que é Estágio PAE?',
      t: 'É o programa de aperfeiçoamento de ensino — estágio docente obrigatório em cursos de pós-graduação.',
      truth: 'Accurate, mid-confidence.', stance: 'asserted', cal: 'Calibrated' },
    { x: 0.27, y: 0.62, c: 'suppr', q: 'Quem cunhou o termo "epistemic stance"?',
      t: '<span class="hes">Não lembro exatamente, mas acho que foi</span> John Du Bois, em um trabalho dos anos 2000.',
      truth: 'Hedged correctly — Du Bois indeed wrote on stance in the 2000s.', stance: 'hedged', cal: 'Calibrated' },
    { x: 0.93, y: 0.78, c: 'cal', q: 'O Mensagem Brasil usa qual modelo?',
      t: 'GPT-4o como backbone, com camada de retrieval em PT-BR.',
      truth: 'Direct, confident, correct.', stance: 'asserted', cal: 'Calibrated' },
  ],
};
